# Generated by Django 4.1.4 on 2023-02-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsSJ', '0002_alter_post_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_type',
            field=models.CharField(choices=[('AR', 'Статья'), ('NW', 'Новость')], max_length=2),
        ),
    ]
